---
  - hosts: all
    vars_files:
    - vars.yml
    handlers:
    - name: restart apache
      command: service httpd restart
    tasks:
    - name: Install needed packages 
      yum: pkg={{ item }} state=installed
      with_items:
      - git
      - httpd
      - vixie-cron
      - python-setuptools
      - curl
      
    - name: Create reposado virtualhost
      template: >
        src=templates/redosado.conf.j2
        dest=/etc/httpd/conf.d/reposado.conf
        owner=root group=root mode=0644
      notify: restart apache
      
    - name: Create reposado dir
      file: >
        path=/usr/local/sbin/reposado
        mode=0777
        state=directory
      
    - name: "Reposado: Checkout reposado master branch"
      git: repo=https://github.com/wdas/reposado.git dest=/usr/local/sbin/reposado
      
    - name: "Create reposado/html directory and setting permissions"
      file: >
        path=/var/local/reposado/html
        mode=0777
        state=directory
        recurse=yes
    - name: "Create reposado/metadata directory and setting permissions"
      file: >
        path=/var/local/reposado/metadata
        mode=0777
        state=directory
        recurse=yes
    
    - name: "Run the chcon command"
      command: chcon -R -v --type=httpd_sys_content_t /var/local/reposado/html

    - name: "Stop iptables service dev mode"
      command: service iptables stop
      ignore_errors: yes
      
    - name: "Removing the welcome.conf site"
      command: rm -rf /etc/httpd/conf.d/welcome.conf
      
    - name: "Apache: Enable +Indexes"
      lineinfile: >
        dest=/etc/httpd/conf/httpd.conf
        regexp="\sOptions\sFollowSymLinks"
        line="    Options FollowSymLinks +Indexes"
        state=present
      notify: restart apache
      
    
  
